images:
  tags:
    initCU: registry.aether.opennetworking.org/aether/pod-init:1.0.0
    vranL3: registry.aether.opennetworking.org/aether/accelleran-cu-l3-tdd:v1.0.2
    depCheck: registry.aether.opennetworking.org/aether/kubernetes-entrypoint:v0.3.1
  pullPolicy: IfNotPresent
config:
  mme:
    ip: "10.168.0.204"
  vranL3:
    plmnId: "130501"
    instanceId: "onfcell203"
    tac: 203
    ports:
      s1ap:
        nodePort: 31412
