images:
  tags:
    hssdb: "registry.aether.opennetworking.org/c3po-hssdb:1.1.0"
    hss: "registry.aether.opennetworking.org/c3po-hss:1.1.2"
    mme: "registry.aether.opennetworking.org/openmme:1.3.6"
    mmeExporter: "registry.aether.opennetworking.org/openmme:0.1.9"
    spgwc: "registry.aether.opennetworking.org/ngic-cp:1.1.1"
  pullPolicy: "Always"

cassandra:
  deploy: false

resources:
  enabled: true

config:
  coreDump:
    enabled: true
    path: /tmp/coredump
  clusterDomain: "azure.central"
  spgwc:
    apn: internet
    multiUpfs: true
    s1uAddr: "192.168.251.4"
    ueIpPool:
      ip: 10.251.0.0
      mask: 255.255.0.0
    cfgFiles:
      app_config.cfg: |
        [GLOBAL]
        NUM_DP_SELECTION_RULES = 2
        [DP_SELECTION_RULE_1]
        DPID = 1
        DPNAME = dp1
        MCC = 315
        MNC = 100
        TAC = 17
        [DP_SELECTION_RULE_2]
        DPID = 1
        DPNAME = dp1
        MCC = 315
        MNC = 100
        TAC = 18

  mme:
    cfgFiles:
      config.json:
        mme:
          mcc:
            dig1: 3
            dig2: 1
            dig3: 5
          mnc:
            dig1: 1
            dig2: 0
            dig3: 0
  hss:
    acl:
      oldTls: "*.azure.central"
    bootstrap:
      enabled: true
      users:
        - imsi: "315010999912343"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912344"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912345"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912346"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912347"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912348"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912349"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "732111000000420"
          msisdn: "1122334455"
          apn: apn1
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "732111000000421"
          msisdn: "1122334455"
          apn: apn1
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
      mmes:
        - id: 1
          isdn: "19136246000"
          unreachability: 1
