images:
  tags:
    initCU: registry.aether.opennetworking.org/aether/pod-init:1.0.0
    nats: registry.aether.opennetworking.org/aether/accelleran-cu-nats-b17:v1.0.0
    redis: registry.aether.opennetworking.org/aether/accelleran-cu-redis-b17:v1.0.0
    vranL3: registry.aether.opennetworking.org/aether/accelleran-cu-l3-fdd-b17:v1.0.0
  pullPolicy: IfNotPresent

nodeSelectors:
  enabled: true
  accelleranCU:
    label: omec-dp-b7
    value: enabled

config:
  epc:
    plmnId: 130501
  nats:
    ip: 192.168.251.31
  mme:
    ip: 172.16.0.8
  progran:
    enabled: false
