fullnameOverride: "cassandra"
image:
  tag: "2.1.20"
persistence:
  enabled: true
  storageClass: "hostpath"
config:
  cluster_size: 1
  seed_size: 1
  cluster_domain: "azure.central"
  endpoint_snitch: "GossipingPropertyFileSnitch"
