progran:
  enabled: false
fabric:
  enabled: true

mcord-subscriber:
  image:
    repository: "omecproject/mcord-synchronizer"
    tag: "comac-1.0.0"
    pullPolicy: "IfNotPresent"

onos-service:
  kafkaService: "cord-platform-kafka"

fabric:
  kafkaService: "cord-platform-kafka"

onosFabricRestHost: "cord-platform-onos-ui.cord-platform-p-x7tlq.svc.menlo.edge"
onosFabricRestPort: 8181
