nodeSelectors:
  enabled: true
  accelleranCBRSCU:
    label: accelleran
    value: enabled

config:
  mme:
    ip: "10.168.0.204"
  vranL3:
    plmnId: "130501"
    instanceId: "onfcell202"
    tac: 202
