images:
  tags:
    hssdb: "registry.aether.opennetworking.org/c3po-hssdb:1.1.0"
    hss: "registry.aether.opennetworking.org/c3po-hss:1.1.4"
    mme: "registry.aether.opennetworking.org/openmme:1.4.4"
    mmeExporter: "registry.aether.opennetworking.org/mme-exporter:0.2.2"
    spgwc: "registry.aether.opennetworking.org/ngic-cp:1.1.1"
  pullPolicy: "Always"

cassandra:
  deploy: false

resources:
  enabled: true
  mme:
    requests:
      cpu: 0.3
      memory: 1Gi
    limits:
      cpu: 0.3
      memory: 1Gi

config:
  coreDump:
    enabled: true
    path: /tmp/coredump
  clusterDomain: "product.central"
  spgwc:
    apn: internet
    multiUpfs: true
    s1uAddr: "192.168.251.7"
    cfgFiles:
      app_config.cfg: |
        [GLOBAL]
        NUM_DP_SELECTION_RULES = 4
        [DP_SELECTION_RULE_1]
        DPID = 1
        DPNAME = dp1
        MCC = 315
        MNC = 010
        TAC = 202
        [DP_SELECTION_RULE_2]
        DPID = 2
        DPNAME = dp2
        MCC = 315
        MNC = 010
        TAC = 203
        [DP_SELECTION_RULE_3]
        DPID = 3
        DPNAME = dp-intel
        MCC = 315
        MNC = 010
        TAC = 101
  mme:
    cfgFiles:
      config.json:
        mme:
          mcc:
            dig1: 3
            dig2: 1
            dig3: 5
          mnc:
            dig1: 1
            dig2: 0
            dig3: 0
  hss:
    acl:
      oldTls: "*.product.central"
    bootstrap:
      enabled: true
      users:
        - imsi: "315010999912342"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912343"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912344"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912345"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912346"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912347"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010999912348"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010888812341"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
        - imsi: "315010888812342"
          msisdn: "1122334455"
          apn: "apn1"
          key: "000102030405060708090a0b0c0d0e0f"
          opc: "69d5c2eb2e2e624750541d3bbc692ba5"
          sqn: 135
      mmes:
        - id: 1
          isdn: "19136246000"
          unreachability: 1
